# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-25 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='모델')),
                ('year', models.IntegerField(default=2018, verbose_name='출시년도')),
                ('color', models.CharField(default='white', max_length=20, verbose_name='색상')),
            ],
        ),
        migrations.CreateModel(
            name='Tires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='브랜드명')),
                ('size', models.FloatField(default=17.0, verbose_name='사이즈')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='tires',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Tires'),
        ),
    ]
