# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-25 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='tires',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.Tires'),
        ),
        migrations.DeleteModel(
            name='Tires',
        ),
    ]
