# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-25 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),  # dependency 를 변경한다.
    ]

    # custom database operations 추가
    database_operations = [
        # django 기본 테이블 네이밍에 맞추어 테이블명 변경 (앱이름_모델이름)
        migrations.AlterModelTable('tires', 'tires_tires')
    ]

    # django state는 아직 변경하지 않는다
    state_operations = [

    ]

    operations = [
        migrations.SeparateDatabaseAndState(
                database_operations=database_operations,
                state_operations=state_operations
        )
    ]
