# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-25 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20180325_1108'),
    ]

    # This needs to be a state-only operation because the database model was
    # renamed, and no longer exists according to Django.
    state_operations = [

        # 이전 마이그레이션 파일에서 가져온다
        migrations.DeleteModel(
                name='Tires',
        )
    ]

    operations = [
        # after this state operation, the django db state should match the
        # actual database structure.
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
